# Generated by Django 6.0.4 on 2026-04-19 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-priority', 'created_at'], 'verbose_name': 'Support Ticket', 'verbose_name_plural': 'Support Tickets'},
        ),
        migrations.CreateModel(
            name='TicketNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Note',
                'verbose_name_plural': 'Ticket Notes',
                'ordering': ['created_at'],
            },
        ),
    ]
