# Generated by Django 6.0.4 on 2026-04-19 19:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_options_ticketnotes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketNotes',
            new_name='TicketNote',
        ),
    ]
